### ISSUE TITLE
Test Dataset "dataset_test_50_RBKN"

### ISSUE THREAD

**Issue by zhangqiqi1228** [Xenoire/DeepFont-FontRecognition#3]
Could you please provide the test dataset which is used as follows?
test_data_path = 'E:\\FontRecognition\\Dataset_Final\\preprocessed\\dataset_test_50_RBKN\\'

BTW, what are the differences between "dataset_test_50_RBKN" and "matrix_dataset_test_50_RBKN"? 
I passed the later one to the "DeepFontAPI.py", but it does not work.

**Comment by bobbyphtr** [comment]
Hi @zhangqiqi1228, 

Ah I see, I'm sorry for answering for a year old issue , I hope I still could help you.. I have lost the data due to my old laptop's hard-drive was broken.. Got BSOD'ed...

You still can generate the synthetic dataset on your own. What I did was:

1. I scraped all of my available fonts in my computer otf / ttf files available.
2. I generated the synthetic dataset 

But RBKN means the generated image patches has been augmented with Random Blur (rb), affine transform (k) and Noise (n).
These parameters are required parameter from https://github.com/Belval/TextRecognitionDataGenerator tool.

dataset_test_50_RBKN
```
trdg --output_dir \"{synthetic_font_path}\" -c {total_images_per_font} bl 3 -rbl -k 6 -rk -f 105 -ft \"{font_type_used}\"     
```

BUT I can provide some explanation what happen here.

The code here:
https://github.com/Bobbyphtr/DeepFont-FontRecognition/blob/67e1e3e0f82e0ca71f5e47befbcdcd3f2beb7368/DeepFontAPI.py#L40-L76

is to create the confusion matrix and the evaluation report as per the test. Something like this
<img width=50% src="https://github.com/user-attachments/assets/6c0787ee-54bf-4f90-9606-b69b10279aef">

If you aim to use the CNN by running the Windows app, you should modify these lines to accept an image input from the App


You may need to change it to something like this
```python
picture_path = str(sys.argv[1])  
# Preprocessing 
img = pil_image(picture_path)
img = crop_resize(img) 
cropped_img = []
cropped_img.extend(img)
x = []
for img in cropped_img:
     img_cv2 = np.array(img)
     x.append(img_cv2)
print(f"Processed image result {len(x)}")
print(f"sample \n {x[0].shape}")

x = np.array(x).reshape(-1, 105, 105, 1)
x = x / 255.0

# Load model
model = load_cnn()

# Predict
result = model.predict_classes(x)

# sort all prediction from the common one to less common
sorted_result = [key for key, count in sorted(Counter(result).most_common(), key=lambda tup : tup[1], reverse=True)]

# Result -- All Top predictions
print("Result ini : ", result)
print("Result sorted : ", sorted_result)
label = [get_label(item) for item in sorted_result]
font_files = [get_fontfile(item) for item in label]
print("Result font_file : ", font_files)
print("#",label)
print("#",font_files)
```

**Comment by bobbyphtr** [comment]
I have updated the `DeepFontApi.py` for it. You can use the pre-trained model directly without having to train it again.
I'm sorry for the very late reply.

Thanks for taking interest in this repo!
